x-airflow-common: &airflow-common
  # image: apache/airflow:2.9.1
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_POSTGRES_USER:-airflow}:${AIRFLOW_POSTGRES_PASSWORD:-airflow_password}@postgres/${AIRFLOW_POSTGRES_DB:-airflow}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    PYTHONPATH: /opt/airflow
    # AIRFLOW_CONN_MY_SPARK_CONN: "spark://local"
    AIRFLOW_CONN_MY_SPARK_CONN: '{"conn_type": "spark", "host": "spark://spark-iceberg", "port": 7077}'
    AIRFLOW_CONN_KAFKA_DEFAULT: '{"conn_type": "kafka", "extra": {"bootstrap.servers": "kafka:9092", "group.id": "airflow-kafka-sensor", "auto.offset.reset": "earliest"}}'
    AIRFLOW_VAR_KAFKA_TOPIC: airbnb_reviews
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false" #auto unpause DAGs when they are created
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../processing:/opt/airflow/processing
    - ../config:/opt/airflow/config
    - ../data:/opt/airflow/data
  networks:
    iceberg_net:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD:-airflow_password}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB:-airflow}
    networks:
      iceberg_net:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_POSTGRES_USER:-airflow}"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: bash -c "airflow db migrate && 
      airflow users create \
      --username ${AIRFLOW_ADMIN_USERNAME:-admin} \
      --password ${AIRFLOW_ADMIN_PASSWORD:-admin} \
      --firstname ${AIRFLOW_ADMIN_FIRSTNAME:-Admin} \
      --lastname ${AIRFLOW_ADMIN_LASTNAME:-User} \
      --role ${AIRFLOW_ADMIN_ROLE:-Admin} \
      --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com} || true &&
      airflow webserver"
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: airflow scheduler
    depends_on:
      postgres:
        condition: service_healthy

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow_triggerer
    command: airflow triggerer
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: