include:
  - processing/processing-docker-compose.yaml
  - streaming/streaming-docker-compose.yaml
  - orchestration/orchestration-docker-compose.yaml

networks:
  iceberg_net:
    driver: bridge

volumes:
  postgres_data: